### PR TITLE
added udacity and other good resources

### PR DESCRIPTION
**Pull request by debidattasuryaprakash**
Screenshot (293)
Screenshot (294)

### CODE REVIEW

**Comment by ghulamyazdani** [comment]
While hovering over the card in your commit the transition which was already there is not functional in your commit can you please fix that?
image

**Comment by debidattasuryaprakash** [comment]
okay there was a merge before I did it so it did not reflect I will fetch and merge it no problem

**Comment by debidattasuryaprakash** [comment]
Please have a look now!

**Comment by sonaljain067** [comment]
Also, update the Learn section with the same content as the home page.

**Comment by debidattasuryaprakash** [comment]
ya sure

**Comment by debidattasuryaprakash** [comment]
Sure Mam

**Comment by debidattasuryaprakash** [comment]
added to learn page

**Comment by sonaljain067** [comment]
LGTM!

**Pull request merged**
