### PR TITLE
fixed fonts, responsiveness, contact page etc.

### PR DESCRIPTION
**Pull request by git-0r**
added corrrect fonts
fixed horizontal scroll in mobile
fixed card size
and other small changes

### CODE REVIEW

**Comment by sonaljain067** [comment]
Why you have removed the original code and then added it to your commit?

**Comment by git-0r** [comment]
That's strange  😯
I don't know how this happened, I only made few changes in fonts, witdth etc.

**Comment by ghulamyazdani** [comment]
@git-0r your branch has conflict please resolve it and commit again.

**Comment by sonaljain067** [comment]
> That's strange 
> I don't know how this happened, I only made few changes in fonts, witdth etc.
> 
> What should I do now?

You can close this PR and raise another PR with your changes.

**Pull request closed without merging**
